# Generated by Django 5.1.2 on 2024-12-10 01:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioParqueoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_espacio', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('bici', 'Bicicleta')], max_length=10, unique=True)),
                ('total_espacios', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Espacios')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido (solo mayúsculas, números y guiones).', regex='^[A-Z0-9-]{6,10}$')], verbose_name='Placa del Vehículo')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta'), ('bici', 'Bicicleta'), ('otro', 'Otro')], max_length=10, verbose_name='Tipo de Vehículo')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Entrada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('tiempo_estacionado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo Estacionado (en horas)')),
                ('total_cobro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Cobrado')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja'), ('facturado', 'Facturado')], default='activo', max_length=20, verbose_name='Estado del Registro')),
                ('cliente_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_registro', to='clientes.cliente', verbose_name='Cliente (para Facturación)')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_parqueo', to='gestion_parqueadero.vehiculo', verbose_name='Vehículo Asociado')),
            ],
        ),
    ]
