# Generated by Django 5.1.2 on 2024-11-06 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_email_alter_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_espacio', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('mantenimiento', 'Mantenimiento')], max_length=15)),
                ('tipo_espacio', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta'), ('bici', 'Bicicleta'), ('otro', 'Otro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta'), ('bici', 'Bicicleta'), ('otro', 'Otro')], max_length=10)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_parqueadero.espacioparqueo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('total_cobro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parqueadero.vehiculo')),
            ],
        ),
    ]
