# Generated by Django 5.1.4 on 2024-12-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('gestion_parqueadero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroparqueo',
            name='usuario_registra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente Asociado'),
        ),
        migrations.AddField(
            model_name='registroparqueo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_parqueo', to='gestion_parqueadero.vehiculo', verbose_name='Vehículo Asociado'),
        ),
    ]
