# Generated by Django 5.1.2 on 2024-11-06 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('gestion_parqueadero', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='registro_parqueo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parqueadero.registroparqueo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
    ]
