# Generated by Django 5.1.2 on 2024-11-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifas.tarifa'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
