# Generated by Django 5.1.2 on 2024-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('camioneta', 'Camioneta'), ('bici', 'Bicicleta'), ('otro', 'Otro')], max_length=10)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
